services:
  pg:
    image: postgres
    container_name: postgres_app
    environment:
      POSTGRES_DB: letswatch
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: